### ISSUE TITLE
Merge coins option returns Split coin selection and visa versa

### ISSUE THREAD

**Issue by kloinka** [lamat1111/Q1-Wallet#1]
![Screenshot from 2024-12-15 20-35-56](https://github.com/user-attachments/assets/c26f320a-23a5-45b7-9d73-2189a723dd24)
![Screenshot from 2024-12-15 20-42-55](https://github.com/user-attachments/assets/06632108-a6cd-4726-b69a-f68a759b3555)

**Comment by lamat1111** [comment]
Fixed in 1.1
Thanks for reporting it!

**Comment by lamat1111** [comment]
Fixed in 1.1
Thanks for reporting it!
